### PR TITLE
Use latest RcppArmadillo

### PR DESCRIPTION
**Pull request by privefl**
Fix https://github.com/YaohuiZeng/biglasso/issues/15.

### CODE REVIEW

**Comment by snowpong** [comment]
> Fix #15.

Did this actually fix the slowdown for you?

We're seeing a 100x slowdown between a Windows machine running R 3.4.4 and a Linux machine running 3.5.2. We did your change, recompiled biglasso locally linking to a freshly compiled RcppArmadillo (0.9.200.5.0) and tried again. It was just as slow. We verified R loaded biglasso from the right directory.

**Comment by privefl** [comment]
Try with version `0.8.600` maybe.

I don't use RcppArmadillo anymore now so I cannot tell.

**Comment by snowpong** [comment]
Small update from us, we tried with `0.8.600` exactly as well, and still no change.

Then we switched to plain R and R packages, not the ones we get in Bioconda, and that solved the issue for us. Might be useful knowledge for someone in the future.

**Comment by privefl** [comment]
What do you mean by "the ones we get in Bioconda"?

**Pull request merged**
